/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.banco.interfaceGrafica.cliente;

import br.banco.interfaceGrafica.TelaLogin;
import br.banco.tratamento.ControleDeDados;
import br.banco.tratamento.Pessoa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author harlock
 */
public class TelaPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    ControleDeDados controle;
    private int  conta;
    private String[] numeroDaConta;
    private int[] contaAtual;
    private int id_usuario;
    String[] dadosDoCliente;

    public void contaLogada(int id_usuario, int[] contaLogada) throws Exception  {
        contaAtual = contaLogada.clone();
        controle = new ControleDeDados();
        conta = contaAtual[0];
        this.id_usuario = id_usuario;
        iniciaSessao();
        

    }
    private void iniciaSessao() throws Exception{
//        controle.SetcontaLogada(Integer.valueOf(numeroDaConta[1]));
        Pessoa p = controle.obtemdadosDaConta(id_usuario,conta);
        textoBemVindoNomeCliente.setText(p.getNome());
        textoAgencia.setText(p.getAgencia());
        textoCPF.setText("Seu CPF: "+p.getCPF().substring(0, 5)+"...");
        textoSaldo.setText("R$"+p.getSaldo());
        textoNumeroDaConta.setText(null);
        if(!p.getConjuta().equalsIgnoreCase("0")){
            botaoIrParaContaCorrente.setEnabled(true);
        }
    }

    public TelaPrincipalCliente() throws Exception {
        initComponents();
        botaoIrParaContaCorrente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoBemVindoNomeCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoEncerrarSessao = new javax.swing.JButton();
        textoSaldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoRealizarSaque = new javax.swing.JButton();
        botaoRealizarDeposito = new javax.swing.JButton();
        botaoIrParaContaCorrente = new javax.swing.JButton();
        botaoExtratoFinanceiro = new javax.swing.JButton();
        textoCPF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textoAgencia = new javax.swing.JLabel();
        textoNumeroDaConta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoBemVindoNomeCliente.setText("Bem vindo! ");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel2.setText("ank");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 111, 165));
        jLabel3.setText("B");

        botaoEncerrarSessao.setText("Encerrar sessão");
        botaoEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncerrarSessaoActionPerformed(evt);
            }
        });

        textoSaldo.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        textoSaldo.setText("R$");

        jLabel5.setText("Seu saldo Atual");

        botaoRealizarSaque.setText("Realizar Saque");

        botaoRealizarDeposito.setText("Realizar Deposito");

        botaoIrParaContaCorrente.setText("Ir para conta Corrente");
        botaoIrParaContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIrParaContaCorrenteActionPerformed(evt);
            }
        });

        botaoExtratoFinanceiro.setText("Extrato financeiro");

        textoCPF.setText("Seu CPF:");

        jLabel1.setText("jLabel1");

        textoAgencia.setText("Agencia:");

        textoNumeroDaConta.setText("Nº da conta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoBemVindoNomeCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoCPF)
                                .addGap(120, 120, 120)
                                .addComponent(textoAgencia)
                                .addGap(122, 122, 122)
                                .addComponent(textoNumeroDaConta)))
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoRealizarDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoRealizarSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoIrParaContaCorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoExtratoFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(textoSaldo)
                            .addComponent(botaoEncerrarSessao))
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoCPF)
                                    .addComponent(textoAgencia)
                                    .addComponent(textoNumeroDaConta))
                                .addGap(8, 8, 8)
                                .addComponent(textoBemVindoNomeCliente)))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoRealizarSaque)
                        .addComponent(botaoIrParaContaCorrente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSaldo)
                    .addComponent(botaoRealizarDeposito)
                    .addComponent(botaoExtratoFinanceiro))
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(botaoEncerrarSessao)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIrParaContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIrParaContaCorrenteActionPerformed
        conta = contaAtual[1];
        try {
            iniciaSessao();
            botaoIrParaContaCorrente.setText("voltar para conta corrente");
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoIrParaContaCorrenteActionPerformed

    private void botaoEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncerrarSessaoActionPerformed
        System.exit(1);
    }//GEN-LAST:event_botaoEncerrarSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("com.sun.java.swing.plaf.gtk.GTKLookAndFeel".equals(info.getClassName())) {   
        try {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaPrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       break;
     } 
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipalCliente().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaPrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEncerrarSessao;
    private javax.swing.JButton botaoExtratoFinanceiro;
    private javax.swing.JButton botaoIrParaContaCorrente;
    private javax.swing.JButton botaoRealizarDeposito;
    private javax.swing.JButton botaoRealizarSaque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel textoAgencia;
    private javax.swing.JLabel textoBemVindoNomeCliente;
    private javax.swing.JLabel textoCPF;
    private javax.swing.JLabel textoNumeroDaConta;
    private javax.swing.JLabel textoSaldo;
    // End of variables declaration//GEN-END:variables
}
