/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.banco.interfaceGrafica;

import br.banco.interfaceGrafica.caixa.TelaPrincipalCaixa;
import br.banco.interfaceGrafica.cliente.TelaPrincipalCliente;
import br.banco.interfaceGrafica.gerente.TelaPrincipalGerente;
import br.banco.tratamento.ControleDeDados;
import br.banco.tratamento.Pessoa;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author harlock
 */
public class TelaLogin extends javax.swing.JFrame {

    ControleDeDados controle;
    Pessoa p;
    private int usuarioLogado;
    private int[] contaAtual;
    private String CPF;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        painelSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSenha = new javax.swing.JPanel();
        campoPegaSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoPegaCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        campoPegaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPegaSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setText("Comfirmar Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        javax.swing.GroupLayout painelSenhaLayout = new javax.swing.GroupLayout(painelSenha);
        painelSenha.setLayout(painelSenhaLayout);
        painelSenhaLayout.setHorizontalGroup(
            painelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSenhaLayout.createSequentialGroup()
                        .addGroup(painelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(campoPegaSenha))
                        .addGap(6, 6, 6))
                    .addGroup(painelSenhaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelSenhaLayout.setVerticalGroup(
            painelSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPegaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        getContentPane().add(painelSenha);
        painelSenha.setBounds(221, 255, 190, 110);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel1.setText("ank");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 56, 46);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 111, 165));
        jLabel2.setText("B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 21, 46);

        campoPegaCPF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            campoPegaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoPegaCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPegaCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPegaCPFKeyPressed(evt);
            }
        });
        getContentPane().add(campoPegaCPF);
        campoPegaCPF.setBounds(230, 210, 180, 40);

        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 190, 31, 18);

        setSize(new java.awt.Dimension(729, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            TelaPrincipalGerente telaGerente = new TelaPrincipalGerente();
            TelaPrincipalCaixa telaCaixa = new TelaPrincipalCaixa();

            controle = new ControleDeDados();
            p = new Pessoa();

            p.setCPF(campoPegaCPF.getText().trim());

            p.setSenha(String.valueOf(campoPegaSenha.getPassword()));
            if (controle.verificaCPF(p)) {

                // Verifica se o usuario realmente existe e qual tela e vai entrar
                controle.cpfCadastrado(p);
                if (controle.confirmarLogin(p)) {
                    usuarioLogado = controle.getUsuarioLogado();
                    contaAtual =  controle.pegaContasExistentes().clone();
                    if (controle.funcionarioLogado().equalsIgnoreCase("GERENTE")) {
                        telaGerente.setVisible(true);
                    } else if (controle.funcionarioLogado().equalsIgnoreCase("CAIXA")) {
                        telaCaixa.setVisible(true);
                    } else {
                        TelaPrincipalCliente telaCliente = new TelaPrincipalCliente();
                        telaCliente.contaLogada(usuarioLogado, contaAtual);
                        this.hide();
                        telaCliente.setVisible(true);
                    }
                    // Diz se existe mais de 1 conta atribuido ao cliente
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoPegaCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPegaCPFKeyPressed
        CPF = campoPegaCPF.getText().trim();
        
        if (campoPegaCPF.getText().replace(" ", "").length() >= 10) {
                painelSenha.setVisible(true);
            }
        
    }//GEN-LAST:event_campoPegaCPFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("com.sun.java.swing.plaf.gtk.GTKLookAndFeel".equals(info.getClassName())) {   
        try {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
       break;
     } 
}
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoPegaCPF;
    private javax.swing.JPasswordField campoPegaSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelSenha;
    // End of variables declaration//GEN-END:variables
}
